#ifndef TEXTURE_FORMAT_FIX_H
#define TEXTURE_FORMAT_FIX_H

#ifdef TEXTURE_FORMAT_FIX

#define FIX_G_IM_FMT_RGBA_TO_YUV G_IM_FMT_YUV
#define FIX_G_IM_FMT_RGBA_TO_CI  G_IM_FMT_CI
#define FIX_G_IM_FMT_RGBA_TO_IA  G_IM_FMT_IA
#define FIX_G_IM_FMT_RGBA_TO_I   G_IM_FMT_I

#define FIX_G_IM_FMT_YUV_TO_RGBA G_IM_FMT_RGBA
#define FIX_G_IM_FMT_YUV_TO_CI   G_IM_FMT_CI
#define FIX_G_IM_FMT_YUV_TO_IA   G_IM_FMT_IA
#define FIX_G_IM_FMT_YUV_TO_I    G_IM_FMT_I

#define FIX_G_IM_FMT_CI_TO_RGBA G_IM_FMT_RGBA
#define FIX_G_IM_FMT_CI_TO_YUV  G_IM_FMT_YUV
#define FIX_G_IM_FMT_CI_TO_IA   G_IM_FMT_IA
#define FIX_G_IM_FMT_CI_TO_I    G_IM_FMT_I

#define FIX_G_IM_FMT_IA_TO_RGBA G_IM_FMT_RGBA
#define FIX_G_IM_FMT_IA_TO_YUV  G_IM_FMT_YUV
#define FIX_G_IM_FMT_IA_TO_CI   G_IM_FMT_CI
#define FIX_G_IM_FMT_IA_TO_I    G_IM_FMT_I

#define FIX_G_IM_FMT_I_TO_RGBA G_IM_FMT_RGBA
#define FIX_G_IM_FMT_I_TO_YUV  G_IM_FMT_YUV
#define FIX_G_IM_FMT_I_TO_CI   G_IM_FMT_CI
#define FIX_G_IM_FMT_I_TO_IA   G_IM_FMT_IA

#else

#define FIX_G_IM_FMT_RGBA_TO_YUV G_IM_FMT_RGBA
#define FIX_G_IM_FMT_RGBA_TO_CI  G_IM_FMT_RGBA
#define FIX_G_IM_FMT_RGBA_TO_IA  G_IM_FMT_RGBA
#define FIX_G_IM_FMT_RGBA_TO_I   G_IM_FMT_RGBA

#define FIX_G_IM_FMT_YUV_TO_RGBA G_IM_FMT_YUV
#define FIX_G_IM_FMT_YUV_TO_CI   G_IM_FMT_YUV
#define FIX_G_IM_FMT_YUV_TO_IA   G_IM_FMT_YUV
#define FIX_G_IM_FMT_YUV_TO_I    G_IM_FMT_YUV

#define FIX_G_IM_FMT_CI_TO_RGBA G_IM_FMT_CI
#define FIX_G_IM_FMT_CI_TO_YUV  G_IM_FMT_CI
#define FIX_G_IM_FMT_CI_TO_IA   G_IM_FMT_CI
#define FIX_G_IM_FMT_CI_TO_I    G_IM_FMT_CI

#define FIX_G_IM_FMT_IA_TO_RGBA G_IM_FMT_IA
#define FIX_G_IM_FMT_IA_TO_YUV  G_IM_FMT_IA
#define FIX_G_IM_FMT_IA_TO_CI   G_IM_FMT_IA
#define FIX_G_IM_FMT_IA_TO_I    G_IM_FMT_IA

#define FIX_G_IM_FMT_I_TO_RGBA G_IM_FMT_I
#define FIX_G_IM_FMT_I_TO_YUV  G_IM_FMT_I
#define FIX_G_IM_FMT_I_TO_CI   G_IM_FMT_I
#define FIX_G_IM_FMT_I_TO_IA   G_IM_FMT_I

#endif

#endif
